credentials:
  usernames:
    sem:
      email: semkjaer@hotmail.nl
      name: sem
      password: $2b$12$JAh13DiOtwszKTKOGbpLzeAGDKOcLTQpkhnb3iO0kEAtVKb8.k9Hu
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - semkjaer@hotmail.nl